/**
 * Client AI Models Catalog
 * Synchronized with server/src/utils/ai.util.ts
 */

export interface AiModelMeta {
  name: string;
  price: number;
  provider: string;
  badge?: string;
  version?: string;
  maxTokens?: number;
  description: string;
  category?: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Fal AI Image Generation Models
// ─────────────────────────────────────────────────────────────────────────────
export const AI_IMAGE_MODELS: Record<string, AiModelMeta> = {
  "Flux 1.1 Pro Ultra": {
    name: "fal-ai/flux-pro/v1.1-ultra",
    price: 25,
    provider: "fal",
    badge: "Ultra 4MP",
    version: "v1.1",
    category: "FLUX Series",
    description: "Premium FLUX model producing up to 4-megapixel images with ultra-fine photographic texture and raw photo capabilities.",
  },
  "Flux Pro v1.1": {
    name: "fal-ai/flux-pro/v1.1",
    price: 20,
    provider: "fal",
    badge: "Studio Pro",
    version: "v1.1",
    category: "FLUX Series",
    description: "Next-generation professional FLUX model with enhanced composition, finer micro-textures, and high resolution.",
  },
  "Flux Pro": {
    name: "fal-ai/flux-pro",
    price: 18,
    provider: "fal",
    badge: "Flagship",
    version: "v1.0",
    category: "FLUX Series",
    description: "Flagship FLUX model designed for enterprise-grade generative art and commercial visual production.",
  },
  "Flux Dev": {
    name: "fal-ai/flux/dev",
    price: 15,
    provider: "fal",
    badge: "High Detail",
    version: "v1.0",
    category: "FLUX Series",
    description: "12B parameter state-of-the-art open weights model delivering incredible prompt adherence and photorealism.",
  },
  "Flux Schnell": {
    name: "fal-ai/flux/schnell",
    price: 10,
    provider: "fal",
    badge: "Fast",
    version: "v1.0",
    category: "FLUX Series",
    description: "Ultra-fast 4-step generation model by Black Forest Labs, optimized for real-time synthesis.",
  },
  "Flux Realism LoRA": {
    name: "fal-ai/flux-realism",
    price: 12,
    provider: "fal",
    badge: "Photorealistic",
    version: "v1.0",
    category: "FLUX Series",
    description: "Specialized FLUX model tuned for authentic portrait photography, lifelike skin tones, and camera lens dynamics.",
  },
  "Ideogram v2": {
    name: "fal-ai/ideogram/v2",
    price: 15,
    provider: "fal",
    badge: "Typography",
    version: "v2.0",
    category: "Typography & Design",
    description: "Industry leader in accurate typography rendering, graphic posters, logos, and stylized compositions.",
  },
  "Ideogram v2 Turbo": {
    name: "fal-ai/ideogram/v2/turbo",
    price: 12,
    provider: "fal",
    badge: "Typography Fast",
    version: "v2.0",
    category: "Typography & Design",
    description: "High-velocity version of Ideogram v2 delivering fast typographic art, badges, and marketing posters.",
  },
  "Recraft V3": {
    name: "fal-ai/recraft-v3",
    price: 15,
    provider: "fal",
    badge: "Design & Vector",
    version: "v3.0",
    category: "Typography & Design",
    description: "Exceptional graphic design model excelling at complex text typography, vector illustrations, and brand aesthetics.",
  },
  "Stable Diffusion 3.5 Large": {
    name: "fal-ai/stable-diffusion-v35-large",
    price: 15,
    provider: "fal",
    badge: "MMDiT",
    version: "v3.5",
    category: "Stable Diffusion",
    description: "Stability AI's flagship Multimodal Diffusion Transformer offering superb prompt fidelity and realistic human anatomy.",
  },
  "Stable Diffusion 3.5 Large Turbo": {
    name: "fal-ai/stable-diffusion-v35-large/turbo",
    price: 12,
    provider: "fal",
    badge: "MMDiT Turbo",
    version: "v3.5",
    category: "Stable Diffusion",
    description: "Accelerated variant of SD 3.5 Large generating high-definition images in just a few sampling steps.",
  },
  "Stable Diffusion 3.5 Medium": {
    name: "fal-ai/stable-diffusion-v35-medium",
    price: 10,
    provider: "fal",
    badge: "Balanced",
    version: "v3.5",
    category: "Stable Diffusion",
    description: "Efficient and agile iteration of SD 3.5 with balanced inference latency and sharp visual quality.",
  },
  "Fast SDXL": {
    name: "fal-ai/fast-sdxl",
    price: 10,
    provider: "fal",
    badge: "Realtime",
    version: "v1.0",
    category: "Stable Diffusion",
    description: "Optimized Stable Diffusion XL pipeline engineered for accelerated high-throughput rendering.",
  },
  "SDXL Lightning": {
    name: "fal-ai/fast-lightning-sdxl",
    price: 8,
    provider: "fal",
    badge: "Ultra Fast",
    version: "v1.0",
    category: "Stable Diffusion",
    description: "Lightning-fast SDXL model generating quality images in 2 to 4 steps with minimum latency.",
  },
  "Playground v2.5": {
    name: "fal-ai/playground-v25",
    price: 10,
    provider: "fal",
    badge: "Aesthetics",
    version: "v2.5",
    category: "Art & Specialized",
    description: "State-of-the-art artistic diffusion model producing rich color grading, portrait contrast, and vivid scenes.",
  },
  "Sana 1.6B": {
    name: "fal-ai/sana",
    price: 8,
    provider: "fal",
    badge: "Efficient DiT",
    version: "v1.0",
    category: "Art & Specialized",
    description: "Deep-compressed linear attention Diffusion Transformer capable of generating up to 4K resolution at blazing speeds.",
  },
  "AuraFlow v0.3": {
    name: "fal-ai/auraflow",
    price: 12,
    provider: "fal",
    badge: "Open DiT",
    version: "v0.3",
    category: "Art & Specialized",
    description: "Large-scale open-source flow-based DiT model built for natural scenes and detailed illustrations.",
  },
  "Fooocus": {
    name: "fal-ai/fooocus",
    price: 10,
    provider: "fal",
    badge: "Prompt Magic",
    version: "v2.0",
    category: "Art & Specialized",
    description: "Midjourney-like image synthesis with automatic prompt expansion and cinematic artistic presets.",
  },
  "Nano Banana 2": {
    name: "fal-ai/nano-banana-2",
    price: 18,
    provider: "fal",
    badge: "Google Photoreal",
    version: "v3.0",
    maxTokens: 8192,
    category: "Google Imagen",
    description: "Google's Imagen model (Nano Banana 2) for high-quality photorealistic image generation.",
  },
  "Nano Banana Pro": {
    name: "fal-ai/nano-banana-pro",
    price: 12,
    provider: "fal",
    badge: "Google Fast",
    version: "v3.0",
    maxTokens: 8192,
    category: "Google Imagen",
    description: "Google's Imagen Pro model (Nano Banana Pro) offering higher quality with faster generation.",
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// OpenRouter AI Text / Chat Models
// Synchronized with server/src/utils/ai.util.ts
// ─────────────────────────────────────────────────────────────────────────────
export const AI_CHAT_MODELS: Record<string, AiModelMeta> = {
  // ── NVIDIA Nemotron ────────────────────────────────────────────────────────
  "NVIDIA Nemotron 3.5 Lightning": {
    name: "nvidia/nemotron-3.5-lightning:free",
    maxTokens: 1048576,
    price: 10,
    provider: "openrouter",
    badge: "Lightning 1M",
    category: "Nvidia Nemotron",
    description: "NVIDIA Nemotron 3.5 Lightning is a 30B mixture-of-experts model with 3B active parameters, optimized for high-throughput reasoning, coding, and agentic workloads.",
  },
  "NVIDIA Nemotron 3 Ultra": {
    name: "nvidia/nemotron-3-ultra-550b-a55b:free",
    maxTokens: 1000000,
    price: 10,
    provider: "openrouter",
    badge: "Ultra 550B",
    category: "Nvidia Nemotron",
    description: "NVIDIA Nemotron 3 Ultra is a 550B-parameter mixture-of-experts reasoning model with 55B active parameters, designed for complex reasoning, coding, agent orchestration, deep research, and long-context workflows.",
  },
  "NVIDIA Nemotron 3 Super": {
    name: "nvidia/nemotron-3-super-120b-a12b:free",
    maxTokens: 262144,
    price: 10,
    provider: "openrouter",
    badge: "Super 120B",
    category: "Nvidia Nemotron",
    description: "NVIDIA Nemotron 3 Super is a 120B hybrid mixture-of-experts model with 12B active parameters, designed for reasoning, coding, planning, multi-agent systems, and long-context tasks.",
  },
  "NVIDIA Nemotron 3 Nano 30B A3B": {
    name: "nvidia/nemotron-3-nano-30b-a3b:free",
    maxTokens: 262144,
    price: 10,
    provider: "openrouter",
    badge: "Nano 30B",
    category: "Nvidia Nemotron",
    description: "NVIDIA Nemotron 3 Nano 30B A3B is a compact 30B-A3B mixture-of-experts model designed for efficient reasoning, coding, tool use, and specialized agentic AI systems.",
  },
  "NVIDIA Nemotron 3 Nano Omni 30B A3B Reasoning": {
    name: "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free",
    maxTokens: 262144,
    price: 10,
    provider: "openrouter",
    badge: "Omni Reasoning",
    category: "Nvidia Nemotron",
    description: "NVIDIA Nemotron 3 Nano Omni is a multimodal 30B-A3B model that accepts text, images, video, and audio and produces text, designed for perception, reasoning, and agent sub-tasks.",
  },
  "NVIDIA Nemotron Nano 12B V2 VL": {
    name: "nvidia/nemotron-nano-12b-v2-vl:free",
    maxTokens: 131072,
    price: 10,
    provider: "openrouter",
    badge: "Vision-Lang",
    category: "Nvidia Nemotron",
    description: "NVIDIA Nemotron Nano 2 VL is a 12B multimodal reasoning model designed for document intelligence, OCR, chart reasoning, image understanding, and video analysis.",
  },
  "NVIDIA Nemotron Nano 9B V2": {
    name: "nvidia/nemotron-nano-9b-v2:free",
    maxTokens: 32768,
    price: 10,
    provider: "openrouter",
    badge: "Nano 9B",
    category: "Nvidia Nemotron",
    description: "NVIDIA Nemotron Nano 9B V2 is a compact reasoning and non-reasoning language model designed for efficient inference, coding, analysis, and general-purpose tasks.",
  },

  // ── InclusionAI Ling ───────────────────────────────────────────────────────
  "InclusionAI Ling 3.0 Flash": {
    name: "inclusionai/ling-3.0-flash:free",
    maxTokens: 262144,
    price: 10,
    provider: "openrouter",
    badge: "Fast MoE",
    category: "InclusionAI Ling",
    description: "Ling 3.0 Flash is a 124B mixture-of-experts model with approximately 5.1B active parameters, optimized for fast inference, general reasoning, coding, and agentic workflows.",
  },
  "InclusionAI Ling 3.0 Flash Fin": {
    name: "inclusionai/ling-3.0-flash-fin:free",
    maxTokens: 262144,
    price: 10,
    provider: "openrouter",
    badge: "Finance",
    category: "InclusionAI Ling",
    description: "Ling 3.0 Flash Fin is a finance-focused 124B mixture-of-experts model designed for financial reasoning, research, mathematics, coding, and long-horizon investment workflows.",
  },
  "InclusionAI Ling 3.0 Flash Sante": {
    name: "inclusionai/ling-3.0-flash-sante:free",
    maxTokens: 262144,
    price: 10,
    provider: "openrouter",
    badge: "Healthcare",
    category: "InclusionAI Ling",
    description: "Ling 3.0 Flash Sante is a healthcare and medicine-focused mixture-of-experts model designed for medical reasoning, clinical knowledge, evidence-based retrieval, coding, and long-horizon tasks.",
  },
  "InclusionAI Ling 3.0 Flash VL": {
    name: "inclusionai/ling-3.0-flash-vl:free",
    maxTokens: 262144,
    price: 10,
    provider: "openrouter",
    badge: "Multimodal",
    category: "InclusionAI Ling",
    description: "Ling 3.0 Flash VL is a multimodal mixture-of-experts model supporting text, image, and video understanding, with reasoning and tool-calling capabilities.",
  },

  // ── Poolside & Cohere ──────────────────────────────────────────────────────
  "Poolside Laguna S 2.1": {
    name: "poolside/laguna-s-2.1:free",
    maxTokens: 262144,
    price: 10,
    provider: "openrouter",
    badge: "Coding Agent",
    category: "Poolside & Cohere",
    description: "Poolside Laguna S 2.1 is a coding-agent model with 118B total parameters and 8B active parameters, optimized for software engineering, agentic coding, reasoning, and long-context workflows.",
  },
  "Poolside Laguna XS 2.1": {
    name: "poolside/laguna-xs-2.1:free",
    maxTokens: 262144,
    price: 10,
    provider: "openrouter",
    badge: "Laguna XS",
    category: "Poolside & Cohere",
    description: "Poolside Laguna XS 2.1 is a compact 33B-A3B coding-agent model optimized for software engineering, reasoning, tool calling, and efficient agentic workflows.",
  },
  "Cohere North Mini Code": {
    name: "cohere/north-mini-code:free",
    maxTokens: 262144,
    price: 10,
    provider: "openrouter",
    badge: "Mini Code",
    category: "Poolside & Cohere",
    description: "Cohere North Mini Code is a 30B mixture-of-experts coding model with 3B active parameters, optimized for code generation, software engineering agents, terminal tasks, and tool use.",
  },

  // ── Google Gemma ───────────────────────────────────────────────────────────
  "Google Gemma 4 31B": {
    name: "google/gemma-4-31b-it:free",
    maxTokens: 262144,
    price: 10,
    provider: "openrouter",
    badge: "Gemma 31B",
    category: "Google Gemma",
    description: "Google Gemma 4 31B Instruct is a dense multimodal model supporting text and image input, reasoning, coding, function calling, structured outputs, and multilingual tasks.",
  },
  "Google Gemma 4 26B A4B": {
    name: "google/gemma-4-26b-a4b-it:free",
    maxTokens: 262144,
    price: 10,
    provider: "openrouter",
    badge: "Gemma 26B",
    category: "Google Gemma",
    description: "Google Gemma 4 26B A4B IT is a multimodal mixture-of-experts instruction model with approximately 3.8B active parameters, supporting reasoning, coding, function calling, structured output, and long-context tasks.",
  },

  // ── Qwen ───────────────────────────────────────────────────────────────────
  "Qwen 3.8 27B": {
    name: "qwen/qwen3.8-27b:free",
    maxTokens: 262144,
    price: 10,
    provider: "openrouter",
    badge: "Vision-Lang",
    category: "Qwen",
    description: "Qwen3.8 27B is an open-weight dense vision-language model designed for coding, professional workflows, research, reasoning, multimodal interaction, and long-running agent tasks.",
  },
  "Qwen3 Next 80B A3B Instruct": {
    name: "qwen/qwen3-next-80b-a3b-instruct:free",
    maxTokens: 262144,
    price: 10,
    provider: "openrouter",
    badge: "Next 80B",
    category: "Qwen",
    description: "Qwen3 Next 80B A3B Instruct is an instruction-tuned mixture-of-experts model optimized for fast stable responses, coding, reasoning, knowledge tasks, RAG, tool use, and long-context conversations.",
  },

  // ── Thinking Machines & Dots ───────────────────────────────────────────────
  "Dots3 Note Preview": {
    name: "dots-studio/dots-3-note-preview:free",
    maxTokens: 524288,
    price: 10,
    provider: "openrouter",
    badge: "MoE 280B",
    category: "Thinking Machines & Dots",
    description: "Dots3-Note Preview is a 280B-parameter open-weight mixture-of-experts model with 16B active parameters, designed for reasoning, coding, multimodal understanding, long-context processing, and agent workflows.",
  },
  "Thinking Machines Inkling": {
    name: "thinkingmachines/inkling:free",
    maxTokens: 1048576,
    price: 10,
    provider: "openrouter",
    badge: "Inkling 975B",
    category: "Thinking Machines & Dots",
    description: "Inkling is a 975B-parameter multimodal mixture-of-experts model with 41B active parameters, designed for reasoning, coding, agentic workflows, tool use, RAG, instruction following, and multilingual applications.",
  },
  "Thinking Machines Inkling Small": {
    name: "thinkingmachines/inkling-small:free",
    maxTokens: 1048576,
    price: 10,
    provider: "openrouter",
    badge: "Inkling Small",
    category: "Thinking Machines & Dots",
    description: "Inkling Small is a 276B-parameter multimodal mixture-of-experts model with 12B active parameters, optimized for efficient reasoning, coding, agentic workflows, RAG, and multilingual conversation.",
  },

  // ── Nex AGI ────────────────────────────────────────────────────────────────
  "Nex AGI Nex-N2.5-Pro": {
    name: "nex-agi/nex-n2.5-pro:free",
    maxTokens: 262144,
    price: 10,
    provider: "openrouter",
    badge: "Autonomous SWE",
    category: "Nex AGI",
    description: "Nex-N2.5-Pro is an agentic model designed for autonomous software engineering, multi-file code changes, GUI-based QA, computer use, deep research, and verified task execution.",
  },
  "Nex AGI Nex-N2.5-Mini": {
    name: "nex-agi/nex-n2.5-mini:free",
    maxTokens: 262144,
    price: 10,
    provider: "openrouter",
    badge: "Agentic Mini",
    category: "Nex AGI",
    description: "Nex-N2.5-Mini is a compact agentic coding model designed for software engineering, computer-use workflows, GUI testing, deep research, and automated task execution.",
  },

  // ── OpenAI & Meta ──────────────────────────────────────────────────────────
  "OpenAI GPT OSS 120B": {
    name: "openai/gpt-oss-120b:free",
    maxTokens: 131072,
    price: 10,
    provider: "openrouter",
    badge: "OSS 120B",
    category: "OpenAI & Meta",
    description: "OpenAI gpt-oss-120b is an open-weight 117B mixture-of-experts reasoning model with 5.1B active parameters, designed for high-reasoning, coding, tool use, agents, and general-purpose workloads.",
  },
  "OpenAI GPT OSS 20B": {
    name: "openai/gpt-oss-20b:free",
    maxTokens: 131072,
    price: 10,
    provider: "openrouter",
    badge: "OSS 20B",
    category: "OpenAI & Meta",
    description: "OpenAI gpt-oss-20b is an open-weight 21B mixture-of-experts model with 3.6B active parameters, optimized for reasoning, coding, function calling, structured outputs, and efficient deployment.",
  },
  "Meta Llama 3.3 70B Instruct": {
    name: "meta-llama/llama-3.3-70b-instruct:free",
    maxTokens: 131072,
    price: 10,
    provider: "openrouter",
    badge: "Llama 70B",
    category: "OpenAI & Meta",
    description: "Meta Llama 3.3 70B Instruct is a multilingual text-only instruction model designed for general-purpose dialogue, reasoning, coding, and conversational applications.",
  },

  // ── LiquidAI ───────────────────────────────────────────────────────────────
  "LiquidAI LFM2.5 2.6B": {
    name: "liquid/lfm-2.5-2.6b:free",
    maxTokens: 65536,
    price: 10,
    provider: "openrouter",
    badge: "LFM 2.6B",
    category: "LiquidAI",
    description: "LFM2.5 2.6B is a compact reasoning model designed for agent workflows, data extraction, RAG, and long-context processing.",
  },
  "LiquidAI LFM2.5 1.2B Thinking": {
    name: "liquid/lfm-2.5-1.2b-thinking:free",
    maxTokens: 32768,
    price: 10,
    provider: "openrouter",
    badge: "Thinking",
    category: "LiquidAI",
    description: "LFM2.5 1.2B Thinking is a lightweight reasoning model optimized for agentic tasks, data extraction, RAG, and efficient edge inference.",
  },
  "LiquidAI LFM2.5 1.2B Instruct": {
    name: "liquid/lfm-2.5-1.2b-instruct:free",
    maxTokens: 32768,
    price: 10,
    provider: "openrouter",
    badge: "Instruct",
    category: "LiquidAI",
    description: "LFM2.5 1.2B Instruct is a compact instruction-tuned model designed for fast conversational responses and efficient on-device inference.",
  },
};
